WMStudentsOnly: Only W&M students with a email.wm.edu address may register.
AlreadyRegistered: Someone is already registered with this email address.
PasswordMismatch: The passwords do not match.
PasswordTooShort: Passwords must be at least 8 characters long.
FormError: Form error. Please try again.
LoginError: Unrecognized email/password combination.
SemesterExists: A semester with this code already exists.
InvalidCrn: Please enter a valid CRN.
AlreadyStalking: You are already "stalking" that CRN.
EmailDoesntExist: There are no users registered with that email.
ResendVerification: Your account isn't verified yet!
CrnLimitReached: You've already reached your CRN Limit! Upgrade, etc.
