Default: &defaults
  user: bannerstalker
  password: bannerstalker
  host: bannerstalker.com
  port: 5432
  database: bannerstalker
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: bannerstalker_test
  <<: *defaults

Staging:
  database: bannerstalker_staging
  poolsize: 100
  <<: *defaults

Production:
  host: localhost
  database: bannerstalker_production
  poolsize: 100
  <<: *defaults
