Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  analytics: "UA-38565662-1"
  twilioAccount: <account>
  twilioToken: <token>
  twilioNumber: <number>
  stripePublicKey: <public>
  stripeSecretKey: <secret>
  level1NotifyInterval: 7200 # 2 hours  
  level2NotifyInterval: 1800 # 30 minutes  
  level3NotifyInterval: -1   # ASAP

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
