Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: "\xa9 2013 Peter Johnson. All rights reserved."
  analytics: "UA-38565662-1"
  semesters: ["201320"]
  level1NotifyInterval: 7200 # 2 hours  
  level2NotifyInterval: 1800 # 30 minutes  
  level3NotifyInterval: -1   # ASAP

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
